Move functions to top of the file

diff --git a/base16-manager b/base16-manager
--- a/base16-manager
+++ b/base16-manager
@@ -99,6 +99,23 @@ check_arg() {
     exit
   fi
 }
+
+# check if there is new line at the end of file
+# add it if not
+#
+# Rationale: We often need to append something to config file, but if newline
+# is missing at end of file, our string will be appended to same line as
+# last line in config file causing failure
+check_eof_nl() {
+  local file=$1
+
+  # add newline to eof if it is missing
+  local eof
+  eof=$(tail -c 1 "$file")
+  if  [ -n "$eof" ]; then
+    printf "\\n" >> "$file"
+  fi
+}
 # return true, if OS is mac
 is_mac() {
   [[ "$(uname)" == "Darwin" ]]
@@ -107,6 +124,23 @@ is_mac() {
 # return true, if OS is linux
 is_linux() {
   [[ "$(uname)" == "Linux" ]]
+}
+
+# check if there is line in file($1) corresponding to pattern($2)
+# if not, add line($3) to the end of file
+#
+# pattern is matched using extended-regexp
+line_in_file() {
+  local file=$1
+  local pattern=$2
+  local line=$3
+
+  if ! file_exists "$file" || \
+      ! grep -iqE "$pattern" "$file"
+  then
+    check_eof_nl "$file"
+    echo "$line" >> "$file"
+  fi
 }
 
 # install the repo $1, e.g. $1="USER/NAME"
@@ -491,39 +525,6 @@ set_random() {
   set_theme "$(list_themes -R | head -n1 | awk "{print $1;}")"
 }
 
-# check if there is new line at the end of file
-# add it if not
-#
-# Rationale: We often need to append something to config file, but if newline
-# is missing at end of file, our string will be appended to same line as
-# last line in config file causing failure
-check_eof_nl() {
-  local file=$1
-
-  # add newline to eof if it is missing
-  local eof
-  eof=$(tail -c 1 "$file")
-  if ! [ -z "$eof" ]; then
-    printf "\\n" >> "$file"
-  fi
-}
-
-# check if there is line in file($1) corresponding to pattern($2)
-# if not, add line($3) to the end of file
-#
-# pattern is matched using extended-regexp
-line_in_file() {
-  local file=$1
-  local pattern=$2
-  local line=$3
-
-  if ! file_exists "$file" || \
-      ! grep -iqE "$pattern" "$file"
-  then
-    check_eof_nl "$file"
-    echo "$line" >> "$file"
-  fi
-}
 
 set_rofi() {
   local package=$1
