add support for base16-sway

diff --git a/base16-manager b/base16-manager
--- a/base16-manager
+++ b/base16-manager
@@ -142,6 +142,7 @@ list_support() {
   echo "nicodebo/base16-fzf"
   echo "nicodebo/base16-zathura"
   echo "theova/base16-qutebrowser"
+  echo "rkubosz/base16-sway"
 }
 
 # print uninstalled packages which are supported
@@ -239,6 +240,9 @@ set_theme() {
 
         # set theme
         set_generic "$package" "$theme" "#" "=" "$QUTEBROWSERCONF"
+        ;;
+      "rkubosz/base16-sway")
+        set_sway "$package" "$theme"
         ;;
       *)
         err "Package $package is not (yet) supported."
@@ -451,6 +455,23 @@ set_vim() {
     for vim_dir in $vim_dirs; do
       if dir_exists "$vim_dir"; then
         echo "colorscheme base16-$theme" > "$vim_dir/colorscheme.vim"
+      fi
+    done
+  fi
+}
+
+set_sway() {
+  local package=$1
+  local theme=$2
+  local file="$CONFIG_PATH/$package/themes/base16-$theme.config"
+  local sway_dirs="$HOME/.sway $XDG_CONFIG_HOME/sway"
+
+  if ! file_exists "$file"; then
+    err "Sway theme not found."
+  else
+    for sway_dir in $sway_dirs; do
+      if dir_exists "$sway_dir"; then
+        ln -s $file "$sway_dir/colorscheme"
       fi
     done
   fi
