Add function generic_set()
works as described in #31

diff --git a/base16-manager b/base16-manager
--- a/base16-manager
+++ b/base16-manager
@@ -83,7 +83,7 @@ uninstall() {
   tmp=$(mktemp)
 
   grep -v "$template" "$CONFIG_PATH"/installed > "$tmp"
-   mv "$tmp" "$CONFIG_PATH"/installed
+  mv "$tmp" "$CONFIG_PATH"/installed
 
   echo "Uninstalled ${template}."
 }
@@ -191,7 +191,7 @@ set_theme() {
         set_termite "${package}" "${theme}"
         ;;
       "theova/base16-qutebrowser")
-        set_qutebrowser "${package}" "${theme}"
+        set_generic "${package}" "${theme}" "#" "=" "$HOME/.config/qutebrowser/config.py"
         ;;
       *)
         err "Package ${package} is not (yet) supported."
@@ -201,6 +201,73 @@ set_theme() {
 
   echo "Set theme to ${theme}. You may need to restart DE and terminals."
 }
+
+set_generic() {
+  local package=$1
+  local theme=$2
+  local cmnt_string=$3
+  local assign_string=$4
+  local config=$5
+  local config_tmp
+  local file="${CONFIG_PATH}/${package}/themes/base16-${theme}.config.py"
+  local left
+  local line
+  local number
+
+
+  # Error handling for inexisting files
+  if ! file_exists "${file}"; then
+    err "$package theme not found."
+    return 1
+  fi
+
+  # work with a temporary config copy
+  config_tmp=/tmp/base16_manager_$(basename "$config")
+  cp "$config" "$config_tmp"
+
+
+  while read -r line; do
+    # get left side of each assignement
+    left=$(echo "$line" | cut -d "$assign_string" -f 1)
+    left=$(echo "$left" | xargs) # remove trailing whitespaces
+    left=$(echo "$left" | sed 's/\//\\\//g') # escape slashes
+
+
+    # if $left found, then
+    # delete all lines ($line) containing $left
+    # delte all comments above $line
+    if ! [[ -z $left ]]; then
+      lines=$(grep -ohn "$left" "$config_tmp"  | cut -d : -f 1)
+         for number in $lines; do
+          sed -i "$number"'s/.*//' "$config_tmp"
+
+          while  sed "$(( number - 1 ))"'!d' "$config_tmp" | grep -q "^$cmnt_string"
+          do
+            sed -i "$(( number - 1 ))"'s/.*//' "$config_tmp"
+            number=$((number - 1))
+          done
+         done
+    fi
+
+  done <"$file"
+
+  #remove special strings (e.g. in template headers)
+  sed -i '/'"^$cmnt_string"'.*scheme by/d' "$config_tmp"
+
+  # remove parts with more than one empty line
+  sed -i '$!N; /^\(.*\)\n\1$/!P; D' "$config_tmp"
+
+  # create a backup
+  cp "$config" "$config.bak"
+
+  # append colorscheme
+  printf "\\n" >> "$config_tmp"
+  cat "$file" >> "$config_tmp"
+
+  # copy temporary file to the right place
+  cp "$config_tmp" "$config"
+}
+
 
 set_dunst() {
   local package=$1
@@ -375,7 +442,7 @@ set_xresources() {
 
   if ! file_exists "${file}"; then
     err "Xresources theme not found."
-  else 
+  else
     cp "${file}" "${HOME}/${xres_color}"
 
     if file_exists "$xres"; then
