Add qutebrowser

diff --git a/base16-manager b/base16-manager
--- a/base16-manager
+++ b/base16-manager
@@ -171,6 +171,9 @@ set_theme() {
       "khamer/base16-termite")
 	set_termite "${package}" "${theme}"
 	;;
+      "theova/base16-qutebrowser")
+	set_qutebrowser "${package}" "${theme}"
+	;;
       *)
         err "Package ${package} is not (yet) supported."
         ;;
@@ -222,6 +225,38 @@ set_fzf() {
         echo "${line}" >> "${HOME}/${config}"
       fi
     done
+  fi
+}
+
+set_qutebrowser() {
+  local package=$1
+  local theme=$2
+  local file="${CONFIG_PATH}/${package}/themes/base16-${theme}.config.py"
+  local config_folder="${HOME}/.config/qutebrowser"
+  local config="$config_folder/config.py"
+
+  if ! file_exists "${file}"; then
+	  err "qutebrowser theme not found."
+  else
+	  mkdir -p "$config_folder" # create folder if it doesn't already exist.
+
+  	  echo "qutebrowser before if"
+	  if [ -f "$config" ]; then
+  	  echo "qutebrowser after if"
+		  # remove existing definitions and belonging comments
+		  sed -i '/[B|b]ase[[:xdigit:]]./d' "$config"
+		  sed -i '/c.colors/d' "$config"
+		  sed -i '/^#[[:print:]]*[c|C]olor/d' "$config"
+		  sed -i '/# (http[s]*).$/d' "$config"
+		  sed -i '/^# for transparency\.$/d' "$config"
+		  sed -i '/^# Border used around UI elements in prompts\.$/,+2d'\
+			  "$config"
+		  sed -i '/^#[[:print:]]*scheme/d' "$config"
+		  sed -i '$!N; /^\(.*\)\n\1$/!P; D' "$config" #remove newlines
+		  # append colorscheme
+		  printf "\\n" >> "${HOME}/.config/qutebrowser/config.py"
+		  cat "${file}" >> "${HOME}/.config/qutebrowser/config.py"
+	  fi
   fi
 }
 
